export const AddFooddata=[
    {desc:"Banana, fresh",Source:"NCCDB"},
    {desc:"Olive Oil",Source:"NCCDB"},
    {desc:"Avocado, Black Skin",Source:"NCCDB"},
    {desc:"Apple, Fresh, With Skin",Source:"NCCDB"},
    {desc:"Tomato Raw, Includes Cherry, Grape, Roma",Source:"NCCDB"},
    {desc:"Baby Spinach, Raw",Source:"NCCDB"},
    {desc:"Chicken Breast",Source:"NCCDB"},
    {desc:"Oatmeal,Regular",Source:"NCCDB"},
    {desc:"Carrot,Raw",Source:"NCCDB"},
    {desc:"Broccoli",Source:"NCCDB"},
    {desc:"Chia Seeds",Source:"NCCDB"},
    {desc:"Strawberry",Source:"NCCDB"},
    {desc:"Walnuts",Source:"NCCDB"},
    {desc:"Onions",Source:"NCCDB"},
    {desc:"BlueBerry,Fresh",Source:"NCCDB"},
    {desc:"Cucumber,Raw",Source:"NCCDB"},
    {desc:"Sweet Potato,Baked",Source:"NCCDB"},
    {desc:"Pepper",Source:"NCCDB"},
    {desc:"Coffee",Source:"NCCDB"},
    {desc:"Rice",Source:"NCCDB"},
    {desc:"Flax Seeds",Source:"NCCDB"},
    {desc:"Butter, Salted",Source:"NCCDB"},
    {desc:"Orange,Fresh",Source:"NCCDB"},
    {desc:"Almond Milk",Source:"NCCDB"},
    {desc:"Honey",Source:"NCCDB"},
    {desc:"Mllk",Source:"NCCDB"}
]

// {desc:"banana",Soruce:"NCCDB",_id:"",userid:"",date:"current date",amount:"";unit:"":energy:""}