export const AddFooddata = [
  { desc: "Banana, fresh", Source: "NCCDB", energy: "105.02" },
  { desc: "Olive Oil", Source: "NCCDB", energy: "884" },
  { desc: "Avocado, Black Skin", Source: "NCCDB", energy: "167" },
  { desc: "Apple, Fresh, With Skin", Source: "NCCDB", energy: "52" },
  {
    desc: "Tomato Raw, Includes Cherry, Grape, Roma",
    Source: "NCCDB",
    energy: "3.06",
  },
  { desc: "Baby Spinach, Raw", Source: "NCCDB", energy: "6.9" },
  { desc: "Chicken Breast", Source: "NCCDB", energy: "173" },
  { desc: "Oatmeal,Regular", Source: "NCCDB", energy: "306.97" },
  { desc: "Carrot,Raw", Source: "NCCDB", energy: "26" },
  { desc: "Broccoli", Source: "NCCDB", energy: "65" },
  { desc: "Chia Seeds", Source: "NCCDB", energy: "43" },
  { desc: "Strawberry", Source: "NCCDB", energy: "65" },
  { desc: "Walnuts", Source: "NCCDB", energy: "126" },
  { desc: "Onions", Source: "NCCDB", energy: "20" },
  { desc: "BlueBerry,Fresh", Source: "NCCDB", energy: "69" },
  { desc: "Cucumber,Raw", Source: "NCCDB", energy: "45" },
  { desc: "Sweet Potato,Baked", Source: "NCCDB", energy: "176" },
  { desc: "Pepper", Source: "NCCDB", energy: "8.3" },
  { desc: "Coffee", Source: "NCCDB", energy: "99" },
  { desc: "Rice", Source: "NCCDB", energy: "230" },
  { desc: "Flax Seeds", Source: "NCCDB", energy: "29" },
  { desc: "Butter, Salted", Source: "NCCDB", energy: "134" },
  { desc: "Orange,Fresh", Source: "NCCDB", energy: "37" },
  { desc: "Almond Milk", Source: "NCCDB", energy: "256" },
  { desc: "Honey", Source: "NCCDB", energy: "106" },
  { desc: "Mllk", Source: "NCCDB", energy: "125" },
];

// {desc:"banana",Soruce:"NCCDB",energy:"",_id:"",userid:"",date:"current date",amount:"";unit:"":energy:""}
